apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-01-06T14:29:33Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "5275"
  uid: 527ecf84-d1ad-4d04-aa80-a18efdc5c873
spec:
  clusterIP: 10.96.55.192
  clusterIPs:
  - 10.96.55.192
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
