apiVersion: v1
kind: Service
metadata:
  name: my-eps-service
spec:
  ports:
  - name: http
    port: 80

---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-endpoint-slice
  labels:
    kubernetes.io/service-name: my-eps-service
addressType: IPv4
endpoints:
- addresses:
  - 10.244.2.3
ports: 
- name: http
  port: 80
  protocol: TCP