apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data: 
  username: bXktdXNlcm5hbWU=  # base64 for 'my-username'
  password: bXktcGFzc3dvcmQ=  # base64 for 'my-password'
stringData:
  my-database-name: mariadb
immutable: true